-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 17:30:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `idcategories` INT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `idevents` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `location` VARCHAR(255) NULL,
  `eventscol` VARCHAR(255) NULL,
  `price` DECIMAL(255) NULL,
  `images` BLOB NULL,
  `users_idusers` INT NOT NULL,
  `categories_idcategories` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `categories_idcategories`),
  INDEX `fk_events_categories1_idx` (`categories_idcategories` ASC) VISIBLE,
  CONSTRAINT `fk_events_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_categories1`
    FOREIGN KEY (`categories_idcategories`)
    REFERENCES `mydb`.`categories` (`idcategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reviews` (
  `idreviews` INT NULL,
  `rating` INT NULL,
  `review` LONGTEXT NULL,
  `events_users_idusers` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idreviews`, `events_users_idusers`, `users_idusers`),
  INDEX `fk_reviews_events1_idx` (`events_users_idusers` ASC) VISIBLE,
  INDEX `fk_reviews_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_events1`
    FOREIGN KEY (`events_users_idusers`)
    REFERENCES `mydb`.`events` (`users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registrations` (
  `idregistrations` INT NULL,
  `status` VARCHAR(45) NULL,
  `events_users_idusers` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idregistrations`, `events_users_idusers`, `users_idusers`),
  INDEX `fk_registrations_events1_idx` (`events_users_idusers` ASC) VISIBLE,
  INDEX `fk_registrations_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_registrations_events1`
    FOREIGN KEY (`events_users_idusers`)
    REFERENCES `mydb`.`events` (`users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registrations_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
